version: '3.8'
services:
  backend:
    build:
      context: ./ScrumPokerApp
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  frontend:
    build:
      context: ./scrum-poker-vue
      dockerfile: Dockerfile
      args:
        VITE_HUB_URL: /scrumPokerHub
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge